services:
  updater:
    image: ghcr.io/jonathanbout/cloudflare-dns-updater:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:5000
    env_file:
      - .env